\documentclass{article}
\usepackage{fancyhdr}
\usepackage[a4paper]{geometry}
\pagestyle{fancy}
\lhead{\today}
\chead{}
\rhead{Perfect hit analysis}
\lfoot{}
\cfoot{\thepage}
\rfoot{}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}

\begin{document}

<<set-options, echo=FALSE, cache=FALSE>>=
opts_chunk$set(echo = FALSE, fig.path = 'figure/', dev = 'pdf', 
               fig.align='center', fig.show='hold')
read_chunk('1_load.R')
@
\setcounter{secnumdepth}{0} %this gets rid of the section numbers
\title{How Brian chose his contigs}
\author{}
\date{\today}
\maketitle

\section{}
I wanted to know what the representative probes Brian chose looked 
like. I wanted to know how similar to the contigs they were so that I could 
choose good probes for my mitochondrial analysis. 

I used blastn to measure relatedness (version 2.2.1 of my custom subject 
database blast script). None of his probes were perfect matches to the 
contigs

%% code that calls in the other scripts
<<load>>=
@

<<ext_code2>>=
read_chunk('2_clean.R')
@

<<clean>>=
@

<<ext_code3>>=
read_chunk('3_func.R')
@

<<func>>=
@

<<ext_code4>>=
read_chunk('4_do.R')
@

\section{Analysis}
Make up of the probes used as a read out for both forward and reverse 
complement contigs. Also the number of non-contig probes.

\clearpage
\section{Session information} 
<<session_info>>=
print(sessionInfo(), locale = FALSE)
@

\end{document}